import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../theme/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    header: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 14,
        paddingTop: Platform.OS === 'ios' ? 14 : 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    backButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    leftHeader: {
            flexDirection: 'row',
            alignItems: 'center',        
        },
        backText: {
            fontSize: 24,                 
            color: Colors.textPrimary,
            fontWeight: '400',
        },
        welcome: {
            fontSize: 24,
            fontWeight: '700',
            color: Colors.textPrimary,
            letterSpacing: -0.5,
        },
    headerCenter: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 8,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
        marginLeft: 8,
        letterSpacing: -0.3,
    },
    addButton: {
        backgroundColor: '#0D1117',
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0f172a',
        letterSpacing: -0.3,
    },
    addButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 6,
    letterSpacing: -0.2,
},
    usersList: {
        paddingHorizontal: 16,
    },
    userCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
        borderWidth: 1,
        borderColor: '#f1f5f9',
    },
    userCardMargin: {
        marginBottom: 12,
    },
    userContent: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    avatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#f1f5f9',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        borderWidth: 2,
        borderColor: '#e2e8f0',
    },
    avatarText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#475569',
        letterSpacing: -0.5,
    },
    userDetails: {
        flex: 1,
        justifyContent: 'center',
    },
    userNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    userName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#0f172a',
        letterSpacing: -0.3,
    },
    roleBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 5,
        alignSelf: 'flex-start',
        marginBottom: 6,
    },
    adminBadge: {
        backgroundColor: '#fef3c7',
    },
    viewerBadge: {
        backgroundColor: '#f1f5f9',
    },
    roleText: {
        fontSize: 11,
        fontWeight: '600',
        marginLeft: 4,
    },
    adminText: {
        color: '#d97706',
    },
    viewerText: {
        color: '#64748b',
    },
    userEmail: {
        fontSize: 13,
        color: '#64748b',
        marginBottom: 3,
        letterSpacing: -0.2,
    },
    userJoined: {
        fontSize: 12,
        color: '#94a3b8',
        letterSpacing: -0.2,
    },
    menuButton: {
        width: 36,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        backgroundColor: '#f8fafc',
    },
    dropdown: {
        marginTop: 12,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        overflow: 'hidden',
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        backgroundColor: '#FFFFFF',
    },
    dropdownText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#475569',
        marginLeft: 12,
        letterSpacing: -0.2,
    },
    deleteText: {
        color: '#ef4444',
    },
    dropdownDivider: {
        height: 1,
        backgroundColor: '#f1f5f9',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'transparent',
    },
});